# Generated by Django 5.0.7 on 2024-08-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='tempo',
        ),
        migrations.AddField(
            model_name='jogo',
            name='palavra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.palavra', verbose_name='Palavra do Jogo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='palavra_oculta',
            field=models.CharField(max_length=255, null=True, verbose_name='Palavra Oculta'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tentativas_restantes',
            field=models.IntegerField(default=6, verbose_name='Tentativas Restantes'),
        ),
    ]
