# Generated by Django 5.0.7 on 2024-08-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_jogo_tempo_jogo_palavra_jogo_palavra_oculta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='palavra_oculta',
        ),
        migrations.AddField(
            model_name='jogo',
            name='sequencia',
            field=models.CharField(default=True, max_length=255, verbose_name='Palavra Oculta'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='palavra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.palavra', verbose_name='Palavra do Jogo'),
        ),
    ]
