# Generated by Django 5.0.7 on 2024-08-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_jogo_palavra_oculta_jogo_sequencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='palavra',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='sequencia',
            field=models.CharField(max_length=255, verbose_name='Palavra Oculta'),
        ),
    ]
