# Generated by Django 5.0.8 on 2024-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jogo_jogador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='tentativas_restantes',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='sequencia',
            field=models.CharField(max_length=255, verbose_name='Sequência'),
        ),
    ]
